FROM python:3.9
WORKDIR /app

COPY backend-flask/main.py backend-flask/.flaskenv backend-flask/requirements.txt ./
RUN pip install -r ./requirements.txt

EXPOSE 5000
CMD ["gunicorn","-b",":5000","main:app"]

