FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin/$PATH
COPY frontend-react/package.json frontend-react/yarn.lock ./
COPY frontend-react/src ./src
COPY frontend-react/public ./public
RUN yarn install 
RUN yarn build
CMD ["yarn","start"]

# FROM nginx:stable-alpine
# COPY --from=build-step /app/build /usr/share/nginx/html
# COPY nginx.default.conf /etc/nginx/conf.d/default.conf