services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-api
    ports:
      - "5000:5000"
  client:
    depends_on:
      - main
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-client
    ports:
      - "3000:3000"